import Image from "next/image";
import { UnsplashImage } from "../types/types";
import Link from "next/link";
import { Alert } from "react-bootstrap";

export const metadata = {
  title: 'Static Fetching - NextJs Image gallery',
  description: 'Generated by create next app',
}

export default async function StaticPage(){

  const response = fetch("https://api.unsplash.com/photos/random?client_id=" + process.env.UNSPLASH_ACCESS_KEY);
  const image : UnsplashImage = await (await response).json();
  console.log(image, 'imagee');

  // want to calculate the image to always get the size regardless
  const width = Math.min(500, image.width)
  // so we can keep the aspect ratio
  const height = (width/image.width) * image.height


  return(
    <div className="d-flex flex-column align-items-center">
      <Alert>
      This page <strong>fetches and caches data at build time.</strong> Even though the Unsplash API always returns a new image, we see the same image after refreshing the page until we compile the project again.
      </Alert>
      
      
      <Image 
        src={image.urls.raw}
        width={width}
        height={height}
        alt={image.description}
        className="rounded shadow mw-100 h-100"
      />

      by <Link href={"/users/" + image.user.username}>{image.user.username}</Link>

    </div>
  )

}