import Image from "next/image";
import { UnsplashImage } from "@/app/types/types";
import Link from "next/link";
import { Alert } from "react-bootstrap";


export const metadata = {
  title: 'Dynamic Fetching - NextJs Image gallery',
  description: 'Generated by create next app',
}

// this can be used for making the page dynamic on every request or using cache feature in the fetch
// export const revalidate = 0;

export default async function DynamicPage(){
  // this means you can decide the caching for a particular request compared to when you use revalidate which affects the whole page
  const response = fetch("https://api.unsplash.com/photos/random?client_id=" + process.env.UNSPLASH_ACCESS_KEY,
    {
      // either no-store, no-cache or next works
      // cache: 'no-cache'
      next:{revalidate: 0}


    }
  );
  const image : UnsplashImage = await (await response).json();
 

  // / want to calculate the image to always get the size regardless
  const width = Math.min(500, image.width)
  // so we can keep the aspect ratio
  const height = (width/image.width) * image.height

  return(
    <div className="d-flex flex-column align-items-center">
    <Alert>
    This page <strong>fetches data dynamically.</strong> Every time you refresh the page, you get a new image from the Unsplash API.
    </Alert>
    
    
    <Image 
      src={image.urls.raw}
      width={width}
      height={height}
      alt={image.description}
      className="rounded shadow mw-100 h-100"
    />

    by <Link href={"/users/" + image.user.username}>{image.user.username}</Link>

  </div>
  )

}